/**:
  ros__parameters:
    object_primitives: "1,1,1"
    object_dimensions: 
      - "1.4,1.5,0.1"
      - "0.05,0.05,0.6"
      - "0.05,0.05,0.6"
    # poses xyz wxyz
    object_poses: 
      - "0.7,0.0,-0.07,1.0,0.0,0.0,0.0"
      - "0.6,0.2,0.06,1.0,0.0,0.0,0.0"
      - "0.6,0.0,0.06,1.0,0.0,0.0,0.0"